/* ============================================================
   Maison Mélisse — données du catalogue & contenus
   ============================================================ */

// helper: format price €
const eur = (n) => (n.toFixed(2).replace('.', ',') + ' €');

// Product catalogue. category: 'miel' | 'ruche' | 'coffret'
// profile tags used for filtering: 'doux' | 'corse' | 'fleuri' | 'frais'
const PRODUCTS = [
  {
    id: 'acacia',
    name: "Miel d'Acacia",
    category: 'miel',
    tagline: "Tout en douceur, limpide et lent à cristalliser",
    profile: ['doux', 'fleuri'],
    origin: "Lisière du Vercors, Drôme — récolte de mai",
    price: 11.50,
    sizes: [{ g: 250, price: 11.50 }, { g: 500, price: 19.00 }],
    color: '#E9B84A', lid: '#6F7A4F', cap: '#F0D79A',
    intensity: 1,
    stock: 32,
    badge: "Doux",
    short: "Le plus délicat de nos miels. Clair comme de l'eau de source, il reste liquide de longs mois.",
    notes: ["Floral léger", "Sucre de canne", "Très peu acide"],
    pairing: "Idéal pour sucrer une infusion sans en masquer le goût, ou napper un yaourt fermier.",
    desc: "Récolté sur les robiniers en fleurs qui bordent nos parcelles au mois de mai, l'acacia est le miel des palais discrets. Sa robe presque transparente et sa douceur sans amertume en font le premier miel des enfants. Comme tous nos miels, il n'est ni chauffé ni mélangé : simplement extrait à froid, décanté, puis mis en pot à la ferme.",
    rating: 4.9, reviews: 214,
  },
  {
    id: 'chataignier',
    name: "Miel de Châtaignier",
    category: 'miel',
    tagline: "Corsé, boisé, une vraie personnalité",
    profile: ['corse'],
    origin: "Forêts des contreforts ardéchois — récolte de juillet",
    price: 10.90,
    sizes: [{ g: 250, price: 10.90 }, { g: 500, price: 18.00 }],
    color: '#7A4A1E', lid: '#3E2A16', cap: '#C99A52',
    intensity: 5,
    stock: 18,
    badge: "Corsé",
    short: "Ambré foncé, puissant, légèrement amer en fin de bouche. Le miel des amateurs de caractère.",
    notes: ["Bois & tanin", "Note maltée", "Finale amère"],
    pairing: "Magnifique sur un fromage de chèvre affiné ou dans une vinaigrette au vieux balsamique.",
    desc: "Quand les châtaigniers fleurissent en juillet, nous montons les ruches en forêt. Le miel qui en sort est sombre, franc, presque tannique — à l'opposé de l'acacia. Riche en minéraux, il cristallise lentement en gros grains. Un miel qui ne fait pas l'unanimité, et c'est très bien ainsi.",
    rating: 4.8, reviews: 168,
  },
  {
    id: 'lavande',
    name: "Miel de Lavande",
    category: 'miel',
    tagline: "Le soleil de Provence dans un pot",
    profile: ['fleuri', 'doux'],
    origin: "Plateau de Sault, Vaucluse — transhumance de juillet",
    price: 13.00,
    sizes: [{ g: 250, price: 13.00 }, { g: 500, price: 22.00 }],
    color: '#D9A94C', lid: '#7C6FA0', cap: '#E7D2A0',
    intensity: 2,
    stock: 24,
    badge: "Fleuri",
    short: "Crémeux, fin, avec ce parfum inimitable de lavande chauffée par le soleil.",
    notes: ["Lavande fraîche", "Texture crémeuse", "Longueur en bouche"],
    pairing: "Sur une tartine de pain au levain, ou pour parfumer une crème brûlée.",
    desc: "Chaque été, nos ruches font la transhumance jusqu'aux champs de lavande du plateau de Sault. Le miel récolté là-haut cristallise naturellement en une texture crémeuse, presque tartinable, et garde le parfum entêtant de la fleur. Un classique provençal que nous récoltons en petite quantité.",
    rating: 5.0, reviews: 301,
  },
  {
    id: 'montagne',
    name: "Miel de Montagne",
    category: 'miel',
    tagline: "Mille fleurs d'altitude, chaque année différent",
    profile: ['corse', 'fleuri'],
    origin: "Alpages du Vercors, 1400 m — récolte d'août",
    price: 9.50,
    sizes: [{ g: 250, price: 9.50 }, { g: 500, price: 16.00 }],
    color: '#B5732A', lid: '#54603A', cap: '#DCC089',
    intensity: 4,
    stock: 41,
    badge: "Multifloral",
    short: "Un miel d'altitude riche et changeant, fruit de la flore sauvage des alpages.",
    notes: ["Fruits confits", "Note de réglisse", "Rond & long"],
    pairing: "Le miel à tout faire : pâtisserie, marinades, ou simplement à la cuillère.",
    desc: "Au cœur de l'été, nous montons les ruches dans les alpages du Vercors. Les abeilles butinent une mosaïque de fleurs sauvages — trèfle, serpolet, framboisier — et composent un miel ambré, rond et profond. Sa récolte varie chaque année au gré de la météo de la montagne.",
    rating: 4.7, reviews: 142,
  },
  {
    id: 'tilleul',
    name: "Miel de Tilleul",
    category: 'miel',
    tagline: "Frais, mentholé, presque apaisant",
    profile: ['fleuri'],
    origin: "Alignements de tilleuls, vallée de la Drôme — récolte de juin",
    price: 10.00,
    sizes: [{ g: 250, price: 10.00 }, { g: 500, price: 17.00 }],
    color: '#E0C25A', lid: '#5A7A6A', cap: '#EEDDA6',
    intensity: 3,
    stock: 0,
    badge: "Fleuri",
    short: "Clair et aromatique, avec une fraîcheur mentholée très particulière.",
    notes: ["Menthe & fraîcheur", "Fleur de tilleul", "Légère amertume"],
    pairing: "Parfait en tisane du soir, sa réputation apaisante n'est plus à faire.",
    desc: "Récolté sur les vieux tilleuls qui bordent les routes de la vallée, ce miel clair surprend par sa fraîcheur presque mentholée. On le dit apaisant — nous on le trouve surtout délicieux dans une tisane avant de dormir.",
    rating: 4.8, reviews: 97,
  },
  {
    id: 'foret',
    name: "Miel de Forêt",
    category: 'miel',
    tagline: "Sombre et malté, le miel des sous-bois",
    profile: ['corse'],
    origin: "Sapinières du Vercors — miellat de fin d'été",
    price: 12.50,
    sizes: [{ g: 250, price: 12.50 }, { g: 500, price: 21.00 }],
    color: '#3E2A16', lid: '#A8631C', cap: '#8A6529',
    intensity: 5,
    stock: 12,
    badge: "Corsé",
    short: "Presque noir, dense, avec des notes maltées et balsamiques. Riche en oligo-éléments.",
    notes: ["Malt & caramel", "Balsamique", "Très peu sucré"],
    pairing: "Sublime dans un pain d'épices ou avec un fromage à pâte pressée.",
    desc: "Le miel de forêt n'est pas issu des fleurs mais du miellat — cette sève sucrée déposée sur les sapins. Sombre, dense et peu sucré, c'est un miel rare et minéral que les abeilles ne produisent que les bonnes années.",
    rating: 4.9, reviews: 88,
  },
  {
    id: 'pollen',
    name: "Pollen frais de nos ruches",
    category: 'ruche',
    tagline: "Récolté frais, congelé aussitôt",
    profile: ['frais'],
    origin: "Rucher de la ferme, Vercors",
    price: 14.00,
    sizes: [{ g: 200, price: 14.00 }],
    color: '#E0A92E', lid: '#A8631C', cap: '#F0C766',
    intensity: 3,
    stock: 20,
    badge: "Ruche",
    short: "Pelotes multicolores gorgées de protéines, à saupoudrer sur vos petits-déjeuners.",
    notes: ["Floral & frais", "Texture tendre", "Riche en protéines"],
    pairing: "Dans un smoothie, sur un porridge, ou mélangé à un peu de miel.",
    desc: "Le pollen est récolté directement à l'entrée de la ruche grâce à une trappe délicate, puis congelé dans la foulée pour préserver toute sa fraîcheur. Nous ne le séchons pas : c'est ce qui lui garde sa texture tendre et ses vertus.",
    rating: 4.7, reviews: 64,
  },
  {
    id: 'propolis',
    name: "Propolis — spray pur",
    category: 'ruche',
    tagline: "Le bouclier naturel de la ruche",
    profile: ['frais'],
    origin: "Rucher de la ferme, Vercors",
    price: 13.00,
    sizes: [{ g: 30, price: 13.00 }],
    color: '#6E3D14', lid: '#3E2A16', cap: '#A8631C',
    intensity: 4,
    stock: 27,
    badge: "Ruche",
    short: "Récoltée puis mise en solution sans additif. Le réflexe des gorges fragiles.",
    notes: ["Résineux", "Balsamique", "Légèrement piquant"],
    pairing: "Quelques pulvérisations dans la bouche dès les premiers frimas.",
    desc: "Les abeilles fabriquent la propolis pour protéger la ruche. Nous la récoltons sur des grilles dédiées, puis la mettons en solution sans aucun additif. Un concentré de la pharmacie de la ruche.",
    rating: 4.8, reviews: 110,
  },
  {
    id: 'pain-epices',
    name: "Pain d'épices au miel",
    category: 'ruche',
    tagline: "Cuit au four à bois, au miel de châtaignier",
    profile: ['doux', 'corse'],
    origin: "Fournil de la ferme, Vercors",
    price: 9.00,
    sizes: [{ g: 350, price: 9.00 }],
    color: '#8A5424', lid: '#3E2A16', cap: '#C99A52',
    intensity: 3,
    stock: 16,
    badge: "Fait maison",
    short: "Moelleux, généreusement épicé, à 40 % de notre miel de châtaignier.",
    notes: ["Cannelle & anis", "Miel corsé", "Moelleux"],
    pairing: "Au goûter avec un thé, ou toasté avec du foie gras.",
    desc: "Notre pain d'épices est pétri à la main et cuit au four à bois, avec une vraie dose de miel de châtaignier et un mélange d'épices que Camille garde jalousement. Sans conservateur : il se garde une semaine, mais il ne tient jamais aussi longtemps.",
    rating: 4.9, reviews: 156,
  },
  {
    id: 'coffret-decouverte',
    name: "Coffret Découverte — trio de miels",
    category: 'coffret',
    tagline: "Acacia, lavande, châtaignier en pots de 125 g",
    profile: ['doux', 'fleuri', 'corse'],
    origin: "Assemblé à la ferme, Vercors",
    price: 28.00,
    sizes: [{ g: 375, price: 28.00 }],
    color: '#C5811F', lid: '#6F7A4F', cap: '#E8C063',
    intensity: 3,
    stock: 22,
    badge: "Coffret",
    short: "Trois pots, trois caractères. Le cadeau parfait pour faire découvrir nos miels.",
    notes: ["Du plus doux", "…au plus corsé", "Coffret bois & jute"],
    pairing: "Le cadeau qui plaît à tous les coups, livré dans son écrin de bois.",
    desc: "Un coffret en bois garni de toile de jute, qui réunit trois de nos miels signature en pots de 125 g : l'acacia tout en douceur, la lavande fleurie et le châtaignier corsé. Une jolie façon de faire le tour de nos récoltes — ou de l'offrir.",
    rating: 5.0, reviews: 203,
  },
  {
    id: 'coffret-ruche',
    name: "Coffret L'Apicultrice",
    category: 'coffret',
    tagline: "Le grand tour : miels & produits de la ruche",
    profile: ['doux', 'corse', 'frais'],
    origin: "Assemblé à la ferme, Vercors",
    price: 46.00,
    sizes: [{ g: 900, price: 46.00 }],
    color: '#A8631C', lid: '#54603A', cap: '#E0C25A',
    intensity: 4,
    stock: 9,
    badge: "Coffret",
    short: "Deux miels, pollen, propolis et pain d'épices. Tout notre savoir-faire réuni.",
    notes: ["Miel + ruche", "Édition limitée", "Carte signée Camille"],
    pairing: "Pour offrir en grand, ou se faire un cadeau qui dure tout l'hiver.",
    desc: "Notre coffret le plus complet : un miel doux, un miel corsé, un pot de pollen frais, un spray de propolis et un pain d'épices, accompagnés d'une carte écrite à la main par Camille. Assemblé en édition limitée, dans un écrin de bois.",
    rating: 5.0, reviews: 71,
  },
];

const PRODUCT_BY_ID = Object.fromEntries(PRODUCTS.map(p => [p.id, p]));

const CATEGORIES = [
  { id: 'tout',     label: "Tout le rucher" },
  { id: 'miel',     label: "Miels monofloraux" },
  { id: 'ruche',    label: "Produits de la ruche" },
  { id: 'coffret',  label: "Coffrets & duos" },
];

const PROFILES = [
  { id: 'doux',   label: "Doux" },
  { id: 'fleuri', label: "Fleuri" },
  { id: 'corse',  label: "Corsé" },
  { id: 'frais',  label: "Produit frais" },
];

const REASSURANCE = [
  { icon: 'hand',   title: "Récolté à la main", text: "Extraction à froid, jamais de chauffage qui dénature le miel." },
  { icon: 'farm',   title: "Mis en pot à la ferme", text: "Du cadre au pot, tout se fait chez nous, en petites séries." },
  { icon: 'bee',    title: "Ruches respectées", text: "On laisse toujours assez de miel aux abeilles pour passer l'hiver." },
  { icon: 'truck',  title: "Livraison soignée", text: "Expédié sous 48 h, calé dans du carton recyclé. Offert dès 49 €." },
];

const STORY_STATS = [
  { n: "2011", l: "Première ruche" },
  { n: "120", l: "Ruches aujourd'hui" },
  { n: "9", l: "Récoltes par an" },
  { n: "0", l: "Miel acheté ailleurs" },
];

const FAQ = [
  { q: "Pourquoi mon miel a-t-il durci dans le pot ?", a: "C'est tout à fait normal et même bon signe : un miel cru cristallise naturellement avec le temps. Il n'a rien perdu de ses qualités. Pour le refluidifier, placez le pot au bain-marie à moins de 40 °C — au-delà, on abîme le miel." },
  { q: "Vos miels sont-ils bio ?", a: "Nos pratiques sont conformes au cahier des charges de l'apiculture biologique (pas de traitement chimique, ruches en bois, cire saine). La certification est en cours. Surtout, nous récoltons à moins de 30 km de la ferme, loin des grandes cultures." },
  { q: "Comment se passe la livraison ?", a: "Nous expédions sous 48 h ouvrées en Colissimo suivi. Comptez 2 à 3 jours. La livraison est offerte dès 49 € d'achat, sinon elle est de 4,90 € (point relais) ou 6,90 € (à domicile)." },
  { q: "Le miel peut-il geler ou s'abîmer pendant le transport ?", a: "Non, le miel se conserve très bien. Nous calons chaque pot dans du carton alvéolé recyclé. Si un pot arrivait cassé, écrivez-nous : on vous renvoie un colis aussitôt." },
  { q: "Puis-je visiter le rucher ?", a: "Avec plaisir ! Nous ouvrons la ferme quelques week-ends par an pour des visites et des récoltes commentées. Inscrivez-vous à la lettre pour connaître les dates." },
];

const REVIEWS = [
  { name: "Hélène M.", place: "Lyon", text: "Le miel de lavande est une tuerie. On sent vraiment la fleur, rien à voir avec ce qu'on trouve en grande surface.", product: "Miel de Lavande", stars: 5 },
  { name: "Bruno T.", place: "Valence", text: "Châtaignier corsé comme il faut. Camille a même glissé un mot écrit à la main dans le colis. Ça change tout.", product: "Miel de Châtaignier", stars: 5 },
  { name: "Sofia R.", place: "Grenoble", text: "Commande reçue en deux jours, emballage nickel. Le coffret découverte a fait un carton à Noël.", product: "Coffret Découverte", stars: 5 },
];

const ORDER_HISTORY = [
  {
    id: "MEL-2381", date: "14 mai 2026", status: "Livrée", statusKey: "delivered", total: 41.40,
    items: [{ id: 'lavande', g: 500, qty: 1 }, { id: 'acacia', g: 250, qty: 2 }],
  },
  {
    id: "MEL-2210", date: "2 avril 2026", status: "En transit", statusKey: "transit", total: 28.00,
    items: [{ id: 'coffret-decouverte', g: 375, qty: 1 }],
  },
  {
    id: "MEL-1987", date: "11 février 2026", status: "Livrée", statusKey: "delivered", total: 33.90,
    items: [{ id: 'chataignier', g: 500, qty: 1 }, { id: 'pain-epices', g: 350, qty: 1 }, { id: 'propolis', g: 30, qty: 1 }],
  },
];

Object.assign(window, {
  eur, PRODUCTS, PRODUCT_BY_ID, CATEGORIES, PROFILES,
  REASSURANCE, STORY_STATS, FAQ, REVIEWS, ORDER_HISTORY,
});
